### PR TITLE
Rock/Paper/Scissors Game

### PR DESCRIPTION
**Pull request by kimberlym4488**
One page game component featuring a modal and basic working js functionality. 

Preview working code by running:
* npm run dev:open

Navigate to:
* http://localhost:3000/playground/rock-paper-scissors

To view live site:
https://rock-paper-scissors.kmorandev.workers.dev

Features:
- [x] ran successful build and deploy with svelte/wrangler publish.
- [x] added and tested link to rock paper scissors to the default index.
- [x] includes svg images, explored svg color changes with the filter css property.

For future PRs:

### CODE REVIEW

**Comment by kimberlym4488** [comment]
Updated per initial review @ac524

**Review by ac524 — CHANGES_REQUESTED** [review]
Hey @kimberlym4488 Looks like there are few files unrelated to the rock paper scissors game. Let's get those cleaned up before merging.

- `login.svelte`
- `post/[postId].svelte`
- `post/index.svelte`

I'm also seeing the SVG files twice. Once in `static` and once in `src/public`. They should only live in one place. Once of them could be from the build step that we should ignore if you didn't put them in two places.

**Comment by kimberlym4488** [comment]
Updated unused files and svg duplicates

**Review by ac524 — CHANGES_REQUESTED** [review]
Couple cleanup tasks @kimberlym4488 

Please discard the changes in the `package-lock.json` (might be easiest to do using the git graph extension).

Remove the `workers-site` folder.

Remove the additions to the `.gitignore` (Shouldn't be needed, my current config for workers doesn't make `workers-site` folder.

**Comment by kimberlym4488** [comment]
Changes made as requested! Thanks for the feedback here

**Review by ac524 — APPROVED** [review]

**Pull request merged**
